# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elegivel.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'elegivel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65legivel.proto\x12\x07\x65leitor\"%\n\x05\x45tapa\x12\r\n\x05\x65tapa\x18\x01 \x01(\x05\x12\r\n\x05turno\x18\x02 \x01(\t\"S\n\x05\x43urso\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x1d\n\x05\x65tapa\x18\x04 \x01(\x0b\x32\x0e.eleitor.Etapa\"~\n\x07Vinculo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\"\n\x04tipo\x18\x03 \x01(\x0e\x32\x14.eleitor.TipoVinculo\x12\x11\n\tid_pessoa\x18\x04 \x01(\x05\x12\x1d\n\x05\x63urso\x18\x05 \x01(\x0b\x32\x0e.eleitor.Curso\"{\n\x06Pessoa\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03\x63pf\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61ta_nascimento\x18\x04 \x01(\t\x12\x0c\n\x04nome\x18\x05 \x01(\t\x12\"\n\x08vinculos\x18\x06 \x03(\x0b\x32\x10.eleitor.Vinculo\"<\n\x08\x45legivel\x12\x1f\n\x06pessoa\x18\x01 \x01(\x0b\x32\x0f.eleitor.Pessoa\x12\x0f\n\x07\x66oto_id\x18\x02 \x01(\x05\"*\n\x16\x45nviarElegivelResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t*?\n\x0bTipoVinculo\x12\x15\n\x11TIPO_DESCONHECIDO\x10\x00\x12\x0c\n\x08\x44ISCENTE\x10\x01\x12\x0b\n\x07\x44OCENTE\x10\x02\x32W\n\x0f\x45legivelService\x12\x44\n\x0e\x45nviarElegivel\x12\x11.eleitor.Elegivel\x1a\x1f.eleitor.EnviarElegivelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elegivel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOVINCULO']._serialized_start=510
  _globals['_TIPOVINCULO']._serialized_end=573
  _globals['_ETAPA']._serialized_start=27
  _globals['_ETAPA']._serialized_end=64
  _globals['_CURSO']._serialized_start=66
  _globals['_CURSO']._serialized_end=149
  _globals['_VINCULO']._serialized_start=151
  _globals['_VINCULO']._serialized_end=277
  _globals['_PESSOA']._serialized_start=279
  _globals['_PESSOA']._serialized_end=402
  _globals['_ELEGIVEL']._serialized_start=404
  _globals['_ELEGIVEL']._serialized_end=464
  _globals['_ENVIARELEGIVELRESPONSE']._serialized_start=466
  _globals['_ENVIARELEGIVELRESPONSE']._serialized_end=508
  _globals['_ELEGIVELSERVICE']._serialized_start=575
  _globals['_ELEGIVELSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
