"""tipo.vinculo enum model to number, int parameter222

Revision ID: 08c379c8f2ca
Revises: 0d7124467f4e
Create Date: 2025-08-03 18:07:43.187967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c379c8f2ca'
down_revision: Union[str, Sequence[str], None] = '0d7124467f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cursos_etapa_id_fkey'), 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'etapa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('etapa_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cursos_etapa_id_fkey'), 'cursos', 'etapas', ['etapa_id'], ['id'])
    # ### end Alembic commands ###
