"""ondelete set null

Revision ID: 22435222e272
Revises: f0711b464bf5
Create Date: 2025-08-01 17:11:31.562904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22435222e272'
down_revision: Union[str, Sequence[str], None] = 'f0711b464bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vinculos_curso_id_fkey'), 'vinculos', type_='foreignkey')
    op.create_foreign_key(None, 'vinculos', 'cursos', ['curso_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vinculos', type_='foreignkey')
    op.create_foreign_key(op.f('vinculos_curso_id_fkey'), 'vinculos', 'cursos', ['curso_id'], ['id'])
    # ### end Alembic commands ###
