"""criar tables

Revision ID: 309e16c81940
Revises: ebf048f3960d
Create Date: 2025-07-30 16:39:33.387449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309e16c81940'
down_revision: Union[str, Sequence[str], None] = 'ebf048f3960d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etapa', 'turno', name='uq_etapa_turno')
    )
    op.create_index(op.f('ix_etapas_id'), 'etapas', ['id'], unique=False)
    op.create_table('grupos_eleitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('nome', name='uq_nome_grupo')
    )
    op.create_index(op.f('ix_grupos_eleitores_id'), 'grupos_eleitores', ['id'], unique=False)
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_pessoas_id'), 'pessoas', ['id'], unique=False)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('eleitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'SUSPENSO', name='statusenum'), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_eleitores_eleitores',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('eleitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleitor_id'], ['eleitores.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_eleitores.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'eleitor_id')
    )
    op.create_table('vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinculos_id'), 'vinculos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinculos_id'), table_name='vinculos')
    op.drop_table('vinculos')
    op.drop_table('grupo_eleitores_eleitores')
    op.drop_table('eleitores')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_pessoas_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_grupos_eleitores_id'), table_name='grupos_eleitores')
    op.drop_table('grupos_eleitores')
    op.drop_index(op.f('ix_etapas_id'), table_name='etapas')
    op.drop_table('etapas')
    # ### end Alembic commands ###
