"""cascade eleitor pessoa

Revision ID: 4e506e9aaa4e
Revises: bb1e2e8f7ac9
Create Date: 2025-08-01 18:06:52.128150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e506e9aaa4e'
down_revision: Union[str, Sequence[str], None] = 'bb1e2e8f7ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
