"""Criar coluna matricula

Revision ID: dbb6d97cc047
Revises: 273973e151b0
Create Date: 2025-08-04 19:27:43.834809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb6d97cc047'
down_revision: Union[str, Sequence[str], None] = '273973e151b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vinculos', sa.Column('matricula', sa.String(), nullable=False))
    op.alter_column('vinculos', 'tipo',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('DISCENTE', 'DOCENTE', name='tipovinculo'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'vinculos', ['matricula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vinculos', type_='unique')
    op.alter_column('vinculos', 'tipo',
               existing_type=sa.Enum('DISCENTE', 'DOCENTE', name='tipovinculo'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('vinculos', 'matricula')
    # ### end Alembic commands ###
