"""tipo.vinculo enum model

Revision ID: de11913aac3e
Revises: 2335173c8dff
Create Date: 2025-08-01 19:13:41.996529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de11913aac3e'
down_revision: Union[str, Sequence[str], None] = '2335173c8dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vinculos', 'tipo',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('DISCENTE', 'DOCENTE', name='tipovinculo', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vinculos', 'tipo',
               existing_type=sa.Enum('DISCENTE', 'DOCENTE', name='tipovinculo', native_enum=False),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
