"""tipo.vinculo enum model to number, int parameter333

Revision ID: ecb5b09cf8d0
Revises: 08c379c8f2ca
Create Date: 2025-08-03 18:09:55.918276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb5b09cf8d0'
down_revision: Union[str, Sequence[str], None] = '08c379c8f2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('etapa_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cursos', 'etapas', ['etapa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'etapa_id')
    # ### end Alembic commands ###
