"""nullable ids relationship

Revision ID: f0711b464bf5
Revises: 309e16c81940
Create Date: 2025-08-01 16:57:33.382240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0711b464bf5'
down_revision: Union[str, Sequence[str], None] = '309e16c81940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos', 'etapa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vinculos', 'id_pessoa',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vinculos', 'curso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vinculos', 'curso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vinculos', 'id_pessoa',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cursos', 'etapa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
