# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eleitor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'eleitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\releitor.proto\x12\x07\x65leitor\"~\n\x07Vinculo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\"\n\x04tipo\x18\x03 \x01(\x0e\x32\x14.eleitor.TipoVinculo\x12\x11\n\tid_pessoa\x18\x04 \x01(\x05\x12\x1d\n\x05\x63urso\x18\x05 \x01(\x0b\x32\x0e.eleitor.Curso\"%\n\x05\x45tapa\x12\r\n\x05\x65tapa\x18\x01 \x01(\x05\x12\r\n\x05turno\x18\x02 \x01(\t\"S\n\x05\x43urso\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x1d\n\x05\x65tapa\x18\x04 \x01(\x0b\x32\x0e.eleitor.Etapa\"{\n\x06Pessoa\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03\x63pf\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61ta_nascimento\x18\x04 \x01(\t\x12\x0c\n\x04nome\x18\x05 \x01(\t\x12\"\n\x08vinculos\x18\x06 \x03(\x0b\x32\x10.eleitor.Vinculo\"K\n\x07\x45leitor\x12\x1f\n\x06pessoa\x18\x01 \x01(\x0b\x32\x0f.eleitor.Pessoa\x12\x1f\n\x06status\x18\x02 \x01(\x0e\x32\x0f.eleitor.Status\"w\n\x0eGrupoEleitores\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\r\n\x05\x61tivo\x18\x04 \x01(\x08\x12)\n\x0flista_eleitores\x18\x05 \x03(\x0b\x32\x10.eleitor.Eleitor\"\'\n\x13\x45nviarGrupoResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t*?\n\x0bTipoVinculo\x12\x15\n\x11TIPO_DESCONHECIDO\x10\x00\x12\x0c\n\x08\x44ISCENTE\x10\x01\x12\x0b\n\x07\x44OCENTE\x10\x02*G\n\x06Status\x12\x17\n\x13STATUS_DESCONHECIDO\x10\x00\x12\t\n\x05\x41TIVO\x10\x01\x12\x0b\n\x07INATIVO\x10\x02\x12\x0c\n\x08SUSPENSO\x10\x03\x32[\n\x13GrupoEleitorService\x12\x44\n\x0b\x45nviarGrupo\x12\x17.eleitor.GrupoEleitores\x1a\x1c.eleitor.EnviarGrupoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eleitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOVINCULO']._serialized_start=642
  _globals['_TIPOVINCULO']._serialized_end=705
  _globals['_STATUS']._serialized_start=707
  _globals['_STATUS']._serialized_end=778
  _globals['_VINCULO']._serialized_start=26
  _globals['_VINCULO']._serialized_end=152
  _globals['_ETAPA']._serialized_start=154
  _globals['_ETAPA']._serialized_end=191
  _globals['_CURSO']._serialized_start=193
  _globals['_CURSO']._serialized_end=276
  _globals['_PESSOA']._serialized_start=278
  _globals['_PESSOA']._serialized_end=401
  _globals['_ELEITOR']._serialized_start=403
  _globals['_ELEITOR']._serialized_end=478
  _globals['_GRUPOELEITORES']._serialized_start=480
  _globals['_GRUPOELEITORES']._serialized_end=599
  _globals['_ENVIARGRUPORESPONSE']._serialized_start=601
  _globals['_ENVIARGRUPORESPONSE']._serialized_end=640
  _globals['_GRUPOELEITORSERVICE']._serialized_start=780
  _globals['_GRUPOELEITORSERVICE']._serialized_end=871
# @@protoc_insertion_point(module_scope)
